version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.21
        environment:
          - DBR_TEST_MYSQL_DSN=root:root@tcp(127.0.0.1:3306)/circle_test
          - DBR_TEST_POSTGRES_DSN=postgres://postgres:mysecretpassword@127.0.0.1:5432/postgres?sslmode=disable
          - DBR_TEST_MSSQL_DSN=sqlserver://sa:qwe123QWE@127.0.0.1/?database=master
          - GO111MODULE=on
          - FOSSA_API_KEY=486be1298513b278ba3916aa63975d7c
      - image: percona:5.7
        environment:
          - MYSQL_DATABASE=circle_test
          - MYSQL_ROOT_PASSWORD=root
      - image: postgres:13-alpine
        environment:
          - POSTGRES_PASSWORD=mysecretpassword
      - image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=qwe123QWE
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - checkout
      - run: fossa analyze
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -wait tcp://127.0.0.1:5432 -wait tcp://127.0.0.1:1433 -timeout 1m
      - run: go test -v -cover -bench . ./...
      - run: fossa test
